# Generated by Django 2.1.8 on 2019-04-16 20:04

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='wysiwyg',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Wysiwyg'),
        ),
    ]
