# Generated by Django 2.1.8 on 2019-04-18 14:32

from django.db import migrations, models
import wagtailtextanalysis.text_analysis


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190417_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('sentiment', models.DecimalField(decimal_places=6, default=0, max_digits=7)),
            ],
            bases=(models.Model, wagtailtextanalysis.text_analysis.TextAnalysis),
        ),
    ]
