# Generated by Django 2.1.8 on 2019-04-18 12:10

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtailtextanalysis.text_analysis


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural")
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "wysiwyg",
                    wagtail.core.fields.RichTextField(
                        blank=True, null=True, verbose_name="Wysiwyg"
                    ),
                ),
                ("key_phrases", models.TextField()),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page", wagtailtextanalysis.text_analysis.TextAnalysis),
        )
    ]
