# Generated by Django 2.1.8 on 2019-04-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("demosite", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="key_phrases",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="wysiwyg",
            field=models.TextField(blank=True, null=True, verbose_name="Wysiwyg"),
        ),
    ]
