# Generated by Django 2.1.8 on 2019-04-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("demosite", "0003_comment")]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="sentiment",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=7),
        )
    ]
